# curl-test-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: curl-test
spec:
  containers:
  - name: curl
    image: curlimages/curl
    command: ['sh', '-c', 'sleep 3600']  # Keeps the pod alive for an hour
