apiVersion: v1  # Specifies the API version to use, which is v1 for core resources.
kind: PersistentVolume  # Defines the resource type as a PersistentVolume (PV), used for long-term storage.
metadata:
  name: pv-demo  # The name of the PersistentVolume. This must be unique within the cluster.
spec:
  capacity:
    storage: 1Gi  # Specifies the storage capacity of the volume. In this case, it's 1Gi (1 gigabyte).
  volumeMode: Filesystem  # The mode of the volume. It uses 'Filesystem', meaning the volume will be mounted as a file system.
  accessModes:
    - ReadWriteOnce  # Specifies that the volume can be mounted as read-write by a single node at a time.
  persistentVolumeReclaimPolicy: Delete  # Defines what happens to the PV when it is released. 'Delete' means the volume will be deleted automatically when it is no longer needed (when the PVC is deleted).
  awsElasticBlockStore:  # Specifies that this volume is backed by an AWS EBS (Elastic Block Store) volume.
    volumeID: vol-0d111711d3e158881  # The unique ID of the EBS volume in AWS that backs this PV.
    fsType: ext4  # The file system type used on the EBS volume. 'ext4' is a commonly used file system in Linux.
