apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-storage-class-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-storage
