apiVersion: v1  # Specifies the API version, which is v1 for core resources.
kind: PersistentVolumeClaim  # Defines the resource type as a PersistentVolumeClaim (PVC), which is used to request storage.
metadata:
  name: pvc-demo  # The name of the PersistentVolumeClaim. It must be unique within the namespace.
spec:
  accessModes:
    - ReadWriteOnce  # Specifies the access mode. In this case, the volume can be mounted as read-write by only one node at a time.
  resources:
    requests:
      storage: 1Gi  # Requests 1Gi of storage from a PersistentVolume (PV) that can meet the criteria specified in the claim.
