apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-storage
provisioner: kubernetes.io/aws-ebs  # Use the appropriate provisioner for your cloud provider
parameters:
  type: gp2
