apiVersion: v1
kind: Pod
metadata:
  name: volume-demo
spec:
  containers:
    - name: demo-container
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: web-volume
  volumes:
    - name: web-volume
      emptyDir: {}
