apiVersion: v1              # The version of the Kubernetes API (v1 for basic resources like Pods)
kind: Pod                   # The type of resource you're creating (this is a Pod)
metadata:
  name: secret-pod          # The name of your Pod (used to refer to this Pod in the cluster)
spec:
  containers:               # List of containers running inside this Pod
  - name: app-container     # The name of the container inside the Pod (you can have multiple containers in one Pod)
    image: nginx            # The container image to use (in this case, it's 'nginx', a web server)
    env:                    # Environment variables for the container (used to pass sensitive data or config)
    - name: DB_PASSWORD     # The name of the environment variable inside the container (in this case, it's 'DB_PASSWORD')
      valueFrom:            # Specifies that the value will come from another source, not directly provided here
        secretKeyRef:       # Reference to a key in a Kubernetes Secret (this means we’re pulling the value from a Secret)
          name: my-secret   # The name of the Secret we're pulling from (must match the Secret you created earlier)
          key: password     # The specific key inside the Secret (in this case, 'password', from the 'my-secret' Secret)
