apiVersion: v1          # The version of the Kubernetes API you're using (v1 is for basic resources like Secrets)
kind: Secret            # The type of resource you are creating (in this case, it's a Secret)
metadata:
  name: my-secret       # The name of your Secret (you'll use this name to refer to it in your applications)
type: Opaque            # Opaque means this Secret holds generic, user-defined data (like passwords, tokens, etc.)
data:
  password: bXlTdXBlclNlY3JldFBhc3N3b3Jk   # The key is 'password' (this is how you’ll reference it), 
                                           # and the value is base64 encoded (this is an encoded form of your actual password).
                                           # In this case, 'bXlTdXBlclNlY3JldFBhc3N3b3Jk' is the encoded version of 'mySuperSecretPassword'.
