apiVersion: apps/v1               # Specifies the API version used for the Deployment resource
kind: Deployment                  # Defines the type of resource we are creating, which is a Deployment
metadata:
  name: redis-canary              # The name of the Deployment is 'redis-canary'
  namespace: redis-canary         # The Deployment will be in the 'redis-canary' namespace
spec:
  replicas: 2                     # Number of replicas is 2, as this is a canary deployment
  selector:
    matchLabels:
      app: redis-canary           # Selector matches Pods that have the label 'app: redis-canary'
  template:
    metadata:
      labels:
        app: redis-canary         # Pods created by this template will have the label 'app: redis-canary'
    spec:
      containers:
      - name: redis-container     # Name of the container is 'redis-container'
        image: redis:6.2.6        # The Docker image for the container is Redis version 6.2.6 (new canary version)
        ports:
        - containerPort: 6379     # Exposes port 6379 on the container for Redis traffic
