apiVersion: v1
kind: Service
metadata:
  name: hello-app-green-service
  namespace: blue-green-deployment
spec:
  type: LoadBalancer
  selector:
    app: hello-app
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
