apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-blue
  namespace: blue-green-deployment
  labels:
    app: hello-app
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
      version: blue
  template:
    metadata:
      labels:
        app: hello-app
        version: blue
    spec:
      containers:
      - name: hello-app
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080
