apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
  namespace: blue-green-deployment
spec:
  type: LoadBalancer
  selector:
    app: hello-app
    version: green # this is the update pointing to the green deployment 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
