apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler
rules:
- apiGroups: ["*"]                   # Matches all API groups.
  resources: ["*"]                   # Matches all resources.
  verbs: ["*"]                       # Allows all verbs (actions like get, list, create, update, delete, etc.).
